ProgrammableWaveData_1::
	.incbin "sound/programmable_wave_samples/01.pcm"

ProgrammableWaveData_2::
	.incbin "sound/programmable_wave_samples/02.pcm"

ProgrammableWaveData_3::
	.incbin "sound/programmable_wave_samples/03.pcm"

ProgrammableWaveData_4::
	.incbin "sound/programmable_wave_samples/04.pcm"

ProgrammableWaveData_5::
	.incbin "sound/programmable_wave_samples/05.pcm"

ProgrammableWaveData_6::
	.incbin "sound/programmable_wave_samples/06.pcm"

ProgrammableWaveData_7::
	.incbin "sound/programmable_wave_samples/07.pcm"

ProgrammableWaveData_8::
	.incbin "sound/programmable_wave_samples/08.pcm"

ProgrammableWaveData_9::
	.incbin "sound/programmable_wave_samples/09.pcm"

ProgrammableWaveData_10::
	.incbin "sound/programmable_wave_samples/10.pcm"

ProgrammableWaveData_11::
	.incbin "sound/programmable_wave_samples/11.pcm"

ProgrammableWaveData_12::
	.incbin "sound/programmable_wave_samples/12.pcm"

ProgrammableWaveData_13::
	.incbin "sound/programmable_wave_samples/13.pcm"

ProgrammableWaveData_14::
	.incbin "sound/programmable_wave_samples/14.pcm"

ProgrammableWaveData_15::
	.incbin "sound/programmable_wave_samples/15.pcm"

ProgrammableWaveData_16::
	.incbin "sound/programmable_wave_samples/16.pcm"

ProgrammableWaveData_thppme_pcm_fff6f0::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff6f0.pcm"

ProgrammableWaveData_thppme_pcm_fff700::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff700.pcm"

ProgrammableWaveData_thppme_pcm_fff710::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff710.pcm"

ProgrammableWaveData_thppme_pcm_fff720::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff720.pcm"

ProgrammableWaveData_thppme_pcm_fff730::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff730.pcm"

ProgrammableWaveData_thppme_pcm_fff740::
	.incbin "sound/programmable_wave_samples/thppme_pcm_fff740.pcm"
