SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…Wait! Don't say a word!\p"
    .string "You wanted this!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} received TM04\n"
    .string "from Mr. Esper.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "You already know, don't you?\n"
    .string "TM04 is Calm Mind.\p"
    .string "It makes the Puppet concentrate\n"
    .string "to raise both Sp. Atk and Sp. Def.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"

