CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "It's a photo of Blaine and\n"
    .string "Mr. Fuji.\p"
    .string "They're standing shoulder to\n"
    .string "shoulder with big grins.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "We study Puppets extensively\n"
    .string "every day.\p"
    .string "People often bring us rare Puppets\n"
    .string "for examination.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "A photo of the Lab's founder…\n"
    .string "Dr. Fuji?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "Puppet Lab\n"
    .string "Meeting Room$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "Puppet Lab\n"
    .string "R & D Room$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "Puppet Lab\n"
    .string "Testing Room$"

CinnabarIsland_PokemonLab_Entrance_Text_TeachMonMoveForMushroom::
    .string "I'm the Puppet Move Maniac.\p"
    .string "I know every single move that\n"
    .string "a Puppet learns by growing up.\p"
    .string "I'm also a UFO maniac.\p"
    .string "Bring me two Green UFOs,\n"
    .string "or one Blue UFO.\p"
    .string "If you do that for me, I'll teach\n"
    .string "a move to one of your Puppets.$"

CinnabarIsland_PokemonLab_Entrance_Text_WantMeToTeachMove::
    .string "Sniff, sniff…\n"
    .string "Hm! You smell of UFOs!\p"
    .string "Do you want me to teach a move\n"
    .string "to a Puppet of yours?$"

CinnabarIsland_PokemonLab_Entrance_Text_TutorWhichMon::
    .string "Which Puppet needs tutoring?$"

CinnabarIsland_PokemonLab_Entrance_Text_TeachWhichMove::
    .string "Which move should I teach?$"

CinnabarIsland_PokemonLab_Entrance_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that Puppet.$"

CinnabarIsland_PokemonLab_Entrance_Text_IllNeedMushroomOrTwo::
    .string "Then, I'll need a UFO or two.\n"
    .string "What are you going to give me?$"

CinnabarIsland_PokemonLab_Entrance_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} handed over two\n"
    .string "Green UFOs in exchange.$"

CinnabarIsland_PokemonLab_Entrance_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} handed over one\n"
    .string "Blue UFO in exchange.$"

CinnabarIsland_PokemonLab_Entrance_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your Puppets need to learn a\n"
    .string "move, I need a Blue UFO or two\l"
    .string "Green UFOs.$"

CinnabarIsland_PokemonLab_Entrance_Text_CantTeachAnEgg::
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an Egg.$"