MtMoon_1F_Text_MarcosIntro::
    .string "WHOA!\n"
    .string "You shocked me!\l"
    .string "…Oh, you're just a kid!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Wow!\n"
    .string "Shocked again!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Kids like you shouldn't be\n"
    .string "wandering around here in the dark.$"

MtMoon_1F_Text_JoshIntro::
    .string "Did you come to explore the cave,\n"
    .string "too?$"

MtMoon_1F_Text_JoshDefeat::
    .string "Losing stinks!\n"
    .string "It's so uncool.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "I came all the way down here to\n"
    .string "show off to girls.$"

MtMoon_1F_Text_MiriamIntro::
    .string "Wow! It's way bigger in here than\n"
    .string "I thought!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oh!\n"
    .string "I lost it!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "How do you get out of here?\n"
    .string "It's so big, I may get lost.$"

MtMoon_1F_Text_JovanIntro::
    .string "What!\n"
    .string "Don't sneak up on me!$"

MtMoon_1F_Text_JovanDefeat::
    .string "My POKéMON won't do!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "I have to find stronger POKéMON.\n"
    .string "Where might they be?$"

MtMoon_1F_Text_IrisIntro::
    .string "What?\n"
    .string "I'm waiting for my friends to find\l"
    .string "me here.$"

MtMoon_1F_Text_IrisDefeat::
    .string "I lost?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "I came because I heard there are\n"
    .string "some very rare fossils here.$"

MtMoon_1F_Text_KentIntro::
    .string "Suspicious men are in the cave.\n"
    .string "What about you?$"

MtMoon_1F_Text_KentDefeat::
    .string "You got me!$"

MtMoon_1F_Text_KentPostBattle::
    .string "I saw them!\n"
    .string "I'm sure they're from TEAM ROCKET!$"

MtMoon_1F_Text_RobbyIntro::
    .string "You need to go through this cave\n"
    .string "to get to CERULEAN CITY.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "I lost.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "ZUBAT is tough!\n"
    .string "But if you can catch one, you'll\l"
    .string "be able to count on it.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Beware!\n"
    .string "ZUBAT is a bloodsucker!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Hi, I'm excavating for fossils here\n"
    .string "under MT. MOON.\p"
    .string "Sometimes, BROCK of PEWTER GYM\n"
    .string "lends me a hand.$"

MtMoon_1F_Text_LizIntro::
    .string "Liz: We're twins! And we love\n"
    .string "double battles!$"

MtMoon_1F_Text_LizDefeat::
    .string "Liz: That was really fun!$"

MtMoon_1F_Text_LizPostBattle::
    .string "Liz: You want to know why we\n"
    .string "love double battles?\p"
    .string "We both battle against other\n"
    .string "Trainers, together!$"

MtMoon_1F_Text_LizNotEnoughMons::
    .string "Liz: Aw man…\p"
    .string "We really want to battle you,\n"
    .string "but you only got one Puppet…$"

MtMoon_1F_Text_LivIntro::
    .string "Liv: I'm so excited!\p"
    .string "We're battling you in a double\n"
    .string "battle!$"

MtMoon_1F_Text_LivDefeat::
    .string "Liv: Did we do our best, Liz?$"

MtMoon_1F_Text_LivPostBattle::
    .string "Liv: With Liz on my side, we work\n"
    .string "together and fight other Trainers.$"

MtMoon_1F_Text_LivNotEnoughMons::
    .string "Liv: Aw, if only you have at\n"
    .string "least two Puppets…$"