VictoryRoad_1F_Text_NaomiIntro::
    .string "I wonder if you are good enough\n"
    .string "for me?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "I lost out…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "I never wanted to lose to anybody,\n"
    .string "especially to a younger kid…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "I can see you're good.\n"
    .string "Let me see exactly how good!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "I had a chance…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "Tch!\n"
    .string "I concede, you are better than I!$"

VictoryRoad_1F_Text_JayIntro::
    .string "I've been training my Puppets\n"
    .string "since I was at Viridian Forest!\p"
    .string "And now, I'm ready to face the\n"
    .string "Puppet League!$"

VictoryRoad_1F_Text_JayDefeat::
    .string "No!\n"
    .string "My fairies! My SWriggle!$"

VictoryRoad_1F_Text_JayPostBattle::
    .string "Even if you beat me,\n"
    .string "I'm still the best Bug Catcher\l"
    .string "in Kanto!$"

VictoryRoad_1F_Text_KathyIntro::
    .string "My Puppets are not only cute,\n"
    .string "but also tough!$"

VictoryRoad_1F_Text_KathyDefeat::
    .string "Wow!\n"
    .string "Your Puppets are tough, too!$"

VictoryRoad_1F_Text_KathyPostBattle::
    .string "There are boulder puzzles in\n"
    .string "Victory Road.\p"
    .string "I don't think I can solve\n"
    .string "them all.$"