VermilionCity_House1_Text_DoYouLikeToFish::
    .string "I'm the Fishing Guru's older\n"
    .string "brother.\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

VermilionCity_House1_Text_LikeYourStyleTakeThis::
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"

VermilionCity_House1_Text_ReceivedGoodRod::
    .string "{PLAYER} received a Good Rod from\n"
    .string "the Fishing Guru's brother.$"

VermilionCity_House1_Text_GoodRodCanCatchBetterMons::
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "A crummy Old Rod could only catch\n"
    .string "weak Puppets, yes?\p"
    .string "But with a Good Rod, you can\n"
    .string "catch much better Puppets.$"

VermilionCity_House1_Text_OhThatsDisappointing::
    .string "Oh…\n"
    .string "That's so disappointing…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

VermilionCity_House1_Text_YouHaveNoRoomForGift::
    .string "Oh, no!\p"
    .string "I had a gift for you, but you have\n"
    .string "no room for it!$"

