SaffronCity_Gym_Text_SabrinaIntro::
    .string "I had a vision of your arrival.\p"
    .string "I have had psychic powers since\n"
    .string "I was a child.\p"
    .string "It started when a spoon I\n"
    .string "carelessly tossed, bent.\p"
    .string "I dislike battling, but if you wish,\n"
    .string "I will show you my powers!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "This loss shocks me!\n"
    .string "But, a loss is a loss.\p"
    .string "I admit, I didn't work hard enough\n"
    .string "to win.\p"
    .string "Your victory has earned you the\n"
    .string "Marsh Badge.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Psychic power isn't something that\n"
    .string "only a few people have.\p"
    .string "Everyone has psychic power.\n"
    .string "People just don't realize it.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "The Marsh Badge makes Puppets up\n"
    .string "to Lv. 70 obey you.\p"
    .string "Stronger Puppets will become wild,\n"
    .string "ignoring your orders in battle.\p"
    .string "Just don't raise your Puppets too\n"
    .string "much to avoid that problem.\p"
    .string "Wait, please take this TM with you.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} received TM29 from\n"
    .string "Sabrina.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM29 is Mana Burst.\p"
    .string "It's an attack that may also lower\n"
    .string "the target's special stats.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Your Bag is full of other items.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "Sabrina is far younger than I,\n"
    .string "but she has earned my respect.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Not good enough!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "In a battle of equals, the one\n"
    .string "with the stronger will wins.\p"
    .string "If you wish to beat Sabrina, focus\n"
    .string "and will yourself to victory.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Does our unseen power scare you?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "I never foresaw this!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "Reason Puppets have a fear of\n"
    .string "ghosts and darkness!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "Puppets take on the appearance of\n"
    .string "their Trainers.\p"
    .string "Your Puppets must be tough, then!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "I knew it!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "I have much to learn still…\p"
    .string "I must master Mana Burst and teach\n"
    .string "it to my Puppet…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "You understand, don't you?\p"
    .string "That power alone isn't enough to\n"
    .string "win in the world of Puppets?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "I don't believe this!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "Sabrina just wiped out the Karate\n"
    .string "Master next door.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "You and I, our Puppets shall\n"
    .string "battle!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "I lost after all!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "I knew that this was going to take\n"
    .string "place.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "Sabrina is young, but she's also\n"
    .string "our highly skilled Leader.\p"
    .string "You won't reach her easily!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Ow!\n"
    .string "Down and out!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "There used to be two Puppet Gyms\n"
    .string "in Saffron.\p"
    .string "The Fighting Dojo next door lost\n"
    .string "its Gym status, though.\p"
    .string "We simply creamed them when we\n"
    .string "decided to have just one Gym.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "Saffron Puppet Gym is famous for\n"
    .string "training psychics.\p"
    .string "You want to see Sabrina, don't\n"
    .string "you? I can tell!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "That's right! I used telepathy to\n"
    .string "read your mind!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Sabrina's Puppets use psychic\n"
    .string "power instead of force.\p"
    .string "Dream Puppets are especially\n"
    .string "weak against Reason Puppets.\p"
    .string "They'll get destroyed before they\n"
    .string "can even aim a punch!\p"
    .string "Also, you better be careful.\p"
    .string "One of Sabrina's Puppets isn't\n"
    .string "a Reason-type.\p"
    .string "She'll be using that as her\n"
    .string "wild card.$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psychic power, huh?\p"
    .string "If I had that, I'd make a bundle\n"
    .string "at the slots!$"

SaffronCity_Gym_Text_GymStatue::
    .string "Saffron Puppet Gym\n"
    .string "Leader: Sabrina\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "Saffron Puppet Gym\n"
    .string "Leader: Sabrina\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}, {PLAYER}$"

