SilphCo_1F_Text_WelcomePresidentInBoardroom::
    .string "Welcome.\p"
    .string "The president is in the boardroom\n"
    .string "on 11F.$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile::
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign::
    .string "Silph Co. Head Office\n"
    .string "1F$"

SilphCo_1F_Text_TrainInDevelopment::
    .string "Have you heard the news?\p"
    .string "There's a train currently in\n"
    .string "development.\p"
    .string "I think it's called the\n"
    .string "Magnet Train.\p"
    .string "And Saffron City is going to\n"
    .string "have a station for it.\p"
    .string "Once it's finished, we'll be\n"
    .string "able to use it to get to the\l"
    .string "Johto region.\p"
    .string "How cool is that?$"

SilphCo_1F_Text_ThatTrainerWhoSavedSilphCo::
    .string "Are you that Trainer who saved\n"
    .string "Silph Co. from Team Rocket?\p"
    .string "You must've had a lot of guts\n"
    .string "to manage that!$"

SilphCo_1F_Text_ThatTeamRocket::
    .string "That Team Rocket sure caused\n"
    .string "a lot of trouble here.\p"
    .string "Thankfully, none of us got\n"
    .string "hurt.$"

SilphCo_1F_Text_BackToWork::
    .string "Now that Team Rocket is gone,\n"
    .string "we can finally get back to work.$"

SilphCo_1F_Text_ScientistsWhoWorkedForTeamRocket::
    .string "Those scientists who worked\n"
    .string "for Team Rocket sure have\l"
    .string "interesting Puppets.\p"
    .string "Maybe we can have Puppets like\n"
    .string "those to help us with our\l"
    .string "projects.$"

SilphCo_1F_Text_ToolsCanBeUsedForGoodOrEvil::
    .string "Any tools can be used for good\n"
    .string "or evil, depending on the user.\p"
    .string "I hate to imagine what Team\n"
    .string "Rocket would do if they used\l"
    .string "our technology…$"