MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "I found these fossils!\n"
    .string "They're both mine!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "I'll share!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "We'll each take a fossil!\n"
    .string "No being greedy!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "All right.\n"
    .string "Then this fossil is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Far away, on Cinnabar Island,\n"
    .string "there's a Puppet Lab.\p"
    .string "They do research on regenerating\n"
    .string "fossils.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "We, Team Rocket, shall find the\n"
    .string "fossils!\p"
    .string "Reviving Puppets from them will\n"
    .string "earn us huge riches!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Urgh!\n"
    .string "Now I'm mad!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "You made me mad!\n"
    .string "Team Rocket will blacklist you!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "We, Team Rocket, are Puppet\n"
    .string "gangsters!\l"
    .string "We strike fear with our strength!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "I blew it!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "So, you are good…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "If you find a fossil, give it to me\n"
    .string "and scram!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "It could be bad news!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "I'm steamed!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "Puppets lived here long before\n"
    .string "people came.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Do you want the DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Do you want the HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Obtained the HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Obtained the DOME FOSSIL!$"

MtMoon_B2F_Text_ArianaIntro::
    .string "Hold it right there!$"

MtMoon_B2F_Text_ArianaIntro2::
    .string "I've heard some reports about a\n"
    .string "kid messing with Team Rocket here.\p"
    .string "So, I came to see what's going\n"
    .string "on.\p"
    .string "……… ……… ………\p"
    .string "That… That fossil…\p"
    .string "You must be that kid!\p"
    .string "We want that fossil to make\n"
    .string "money out of it!\p"
    .string "Now, be a good kid and hand that\n"
    .string "fossil to me.\p"
    .string "……… ……… ………\p"
    .string "You're not handing it over?\p"
    .string "Well, I might as well take it\n"
    .string "from you, by force!$"

MtMoon_B2F_Text_ArianaDefeat::
    .string "Hmph, you're stronger than\n"
    .string "I thought…$"

MtMoon_B2F_Text_ArianaPostBattle::
    .string "You know what?\n"
    .string "Keep your fossil.\p"
    .string "We got other things to take care\n"
    .string "of.\p"
    .string "So, you better not mess with us!$"