CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Hah!\p"
    .string "I am Blaine, the red-hot Leader\n"
    .string "of Cinnabar Gym!\p"
    .string "My fiery Puppets are all rough\n"
    .string "and ready with intense heat!\p"
    .string "They incinerate all challengers!\p"
    .string "Hah!\n"
    .string "You better have Burn Heal!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "I have burned down to nothing!\n"
    .string "Not even ashes remain!\p"
    .string "You have earned the Volcano Badge.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "Fire Blast is the ultimate fire\n"
    .string "technique.\p"
    .string "Don't waste it on Water Puppets.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Hah!\p"
    .string "The Volcano Badge heightens the\n"
    .string "Special stats of your Puppets.\p"
    .string "Here, you can have this, too!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} received TM38\n"
    .string "from Blaine.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TM38 contains Fire Blast.\n"
    .string "Teach it to Fire-type Puppets.\p"
    .string "Sunny or Utsuho would be\n"
    .string "ideal for that move.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Make space for this, child!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "Do you know how hot a Puppet's\n"
    .string "fire breath can get?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "Yow!\n"
    .string "Hot, hot, hot!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Fire, or to be more precise,\n"
    .string "combustion…\p"
    .string "…Oxygen in the air…\n"
    .string "Blah, blah, blah, blah…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "I was a thief, but I went straight\n"
    .string "as a Trainer.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "I surrender!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "I get this uncontrollable urge to\n"
    .string "steal other people's Puppets.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "I've studied Puppets thoroughly.\n"
    .string "You can't win!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Waah!\n"
    .string "My studies were insufficient!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "My theories are too complicated\n"
    .string "for you to understand.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "I like using Fire-type Puppets.\n"
    .string "I just do.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "Too hot to handle!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "I wish there's a Fire-type Puppet\n"
    .string "who is a thief.\p"
    .string "I'd use that!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "I know why Blaine became a\n"
    .string "Trainer.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Ow!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Our Leader, Blaine, became lost\n"
    .string "in the mountains but good.\p"
    .string "Night fell when a Mokou\n"
    .string "appeared.\p"
    .string "Her light allows Blaine to find\n"
    .string "his way down safely.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "I've been to many gyms, but this\n"
    .string "one best suits my style.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Yowza!\n"
    .string "Too hot!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "Mokou, Utsuho…\n"
    .string "Those are popular Fire Puppets.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Fire is weak against H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Oh!\n"
    .string "Snuffed out!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "Water beats fire, of course.\p"
    .string "But fire melts ice, so the Fire\n"
    .string "type beats Ice-type Puppets.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "The hotheaded Blaine is a Fire\n"
    .string "Puppet pro.\p"
    .string "Douse his spirits with water!\n"
    .string "You'd better take some\n"
    .string "Burn Heals, too.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}!\n"
    .string "You beat that firebrand!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "Cinnabar Puppet Gym\n"
    .string "Leader: Blaine\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "Cinnabar Puppet Gym\n"
    .string "Leader: Blaine\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "Puppet Quiz!\p"
    .string "Get it right, and the door opens to\n"
    .string "the next room.\p"
    .string "Get it wrong, and face a Trainer!\p"
    .string "If you want to conserve your\n"
    .string "Puppets for the Gym Leader…\p"
    .string "Then get it right!\n"
    .string "Here we go!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "CSuika can evolve by using a\n"
    .string "Tech Shard?$"

CinnabarIsland_Gym_Text_QuizQuestion1a::
    .string "CSuika can evolve by using a\n"
    .string "Swift Shard?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "There are eight certified Puppet\n"
    .string "League Badges?$"

CinnabarIsland_Gym_Text_QuizQuestion2a::
    .string "There are nine certified Puppet\n"
    .string "League Badges?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "AKomachi is part Steel-type?$"

CinnabarIsland_Gym_Text_QuizQuestion3a::
    .string "SKomachi is part Steel-type?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Are Wind-type moves effective\n"
    .string "against Flying-type Puppets?$"

CinnabarIsland_Gym_Text_QuizQuestion4a::
    .string "Are Wind-type moves effective\n"
    .string "against Earth-type Puppets?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "Puppets of the same kind and level\n"
    .string "are not identical?$"

CinnabarIsland_Gym_Text_QuizQuestion5a::
    .string "Puppets of the same kind and level\n"
    .string "are identical?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "TM29 contains Mana Burst?$"

CinnabarIsland_Gym_Text_QuizQuestion6a::
    .string "TM29 contains Mama Burst?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "You're absolutely correct!\p"
    .string "Go on through!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Sorry!\n"
    .string "Bad call!$"

