TwoIsland_House_Text_Shop::
    .string "Hello!\n"
	.string "I got some TMs for sale,\l"
	.string "if you want to buy some.$"

TwoIsland_House_Text_MyHusbandsBrother::
    .string "My husband's brother is\n"
	.string "the Move Maniac.\p"
	.string "We are here to watch his\n"
	.string "place while he's staying at\l"
	.string "Cinnabar Island for a while.\p"
	.string "We are also selling TMs here.\p"
	.string "If you want to buy some TMs,\n"
	.string "feel free to talk to my\l"
	.string "husband.$"