Route6_UnusedHouse_Text_WelcomeToOurBerryHouse::
    .string "Berries, berries, berries!\n"
    .string "We have berries for sale!\p"
    .string "Welcome to our Berry House!$"

Route6_UnusedHouse_Text_CareToBuySomeBerries::
    .string "Care to buy some berries?$"

Route6_UnusedHouse_Text_WeGotNewBerries::
    .string "Look!\n"
    .string "We got new berries available\l"
    .string "for purchase!$"

Route6_UnusedHouse_Text_WeGotLotsOfBerries::
    .string "We got lots of berrie for\n"
    .string "sale!$"

Route6_UnusedHouse_Text_IDontHaveAnyBerries::
    .string "Hello!\n"
    .string "Welcome to our Berry House!\p"
    .string "I don't have any berries to\n"
    .string "sell at the moment.\p"
    .string "But, you can still buy some\n"
    .string "from my sister, if you like.$"

Route6_UnusedHouse_Text_IGotSomeBerries::
    .string "Welcome to our Berry House!\p"
    .string "I got some berries that you\n"
    .string "might like.\p"
    .string "Care to buy some for your\n"
    .string "travels?$"

Route6_UnusedHouse_Text_IGotMoreBerriesForSale::
    .string "Welcome to our Berry House!\n"
    .string "I got more berries for sale.\p"
    .string "Care to buy some for your\n"
    .string "travels?$"