Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The types of POKéMON match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "Aides to Prof. Oak.\p"
    .string "If your iDollDex has complete data\n"
    .string "on fifteen species, I'm supposed to\l"
    .string "give you a reward from Prof. Oak.\p"
    .string "He entrusted me with HM05.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "fifteen kinds of Puppets?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of Puppets!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} received HM05\n"
    .string "from the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "HM05 contains the hidden move\n"
    .string "Flash.\p"
    .string "Flash lights up even the darkest\n"
    .string "of caves and dungeons.\p"
    .string "Once a Puppet learns Flash, you\n"
    .string "can get through Rock Tunnel.$"