ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those Miko Orbs at your waist!\n"
    .string "You have Puppets, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use Puppets anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "This Puppet Gym is always closed.\p"
    .string "I wonder who the Leader is?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "Viridian Gym's Leader returned!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know something about\n"
    .string "CSunny and CLuna?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CSunny can burn you,\n"
    .string "but CLuna can paralyze you.\p"
    .string "Watch that your Puppets aren't\n"
    .string "hit by CSunny's Ember or\l"
    .string "CLuna's Thundershock.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "I go shopping in Pewter City\n"
    .string "occasionally.\p"
    .string "I have to take the winding trail in\n"
    .string "Viridian Forest when I go.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "This is private property!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "iDollDex.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a Puppet,\n"
    .string "the iDollDex automatically updates\l"
    .string "its data.\p"
    .string "…You do know how to catch a\n"
    .string "Puppet, don't you?$"

ViridianCity_Text_TutorialAccept::
    .string "…Just as I thought.\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

ViridianCity_Text_TutorialReject::
    .string "That's good.\p"
    .string "Well, go out and catch those\n"
    .string "Puppets!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "iDollDex?\p"
    .string "At first, focus on weakening the\n"
    .string "Puppet before trying to catch it.$"

ViridianCity_Text_CitySign::
    .string "Viridian City \n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAINER TIPS\p"
    .string "Catch Puppets and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAINER TIPS\p"
    .string "The battle moves of Puppets are\n"
    .string "limited by their Power Points, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "Puppets at a Puppet Center.$"

ViridianCity_Text_GymSign::
    .string "Viridian City Puppet Gym$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "Viridian Gym's doors are locked…$"

ViridianCity_Text_ImFishingGuruDoYouLikeToFish::
    .string "I'm the Fishing Guru!\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

ViridianCity_Text_TakeThisAndFish::
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"

ViridianCity_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} received an Old Rod from\n"
    .string "the Fishing Guru.$"

ViridianCity_Text_FishingIsAWayOfLife::
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "From the seas to rivers, go out\n"
    .string "and land the big one, my friend.$"

ViridianCity_Text_OhThatsSoDisappointing::
    .string "Oh…\n"
    .string "That's so disappointing…$"

ViridianCity_Text_HowAreTheFishBiting::
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

ViridianCity_Text_NoRoomForNiceGift::
    .string "Oh, no!\p"
    .string "I had a nice gift for you, but you\n"
    .string "have no room for it!$"