SilphCo_3F_Text_WhatAmIToDo::
    .string "I work for Silph Co.\n"
    .string "What am I to do?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}!\n"
    .string "You and your Puppets saved us!$"

SilphCo_3F_Text_GruntIntro::
    .string "Quit messing with us, kid!$"

SilphCo_3F_Text_GruntDefeat::
    .string "I give up!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "A hint? You can open doors with\n"
    .string "a CARD KEY!$"

SilphCo_3F_Text_JoseIntro::
    .string "I support Team Rocket more than\n"
    .string "I support Silph Co.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "You really got me!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Humph…\p"
    .string "Team Rocket said that if I helped\n"
    .string "them, they'd let me study Puppets.$"

SilphCo_3F_Text_FloorSign::
    .string "Silph Co. Head Office\n"
    .string "3F$"

SilphCo_3F_Text_BusyBusyBusy::
    .string "Busy, busy, busy!$"